export const CardRarities = [
  {
    rank: -1,
    name: "DEFAULT",
    color1: "#E7F2F8",
    color2: "#E7F2F8",
    color3: "#E7F2F8",
    color4: "#E7F2F8",
    color5: "#353643",
  },
  {
    rank: 1,
    name: "COMMON",
    color1: "#E7F2F8",
    color2: "#B3C5D7",
    color3: "#74BDCB",
    color4: "#74BDCB",
    color5: "black",
  },
  {
    rank: 2,
    name: "RARE",
    color1: "white",
    color2: "black",
    color3: "black",
    color4: "black",
    color5: "black",
  },
  {
    rank: 3,
    name: "SUPER RARE",
    color1: "white",
    color2: "black",
    color3: "black",
    color4: "black",
    color5: "black",
  },
  {
    rank: 4,
    name: "HOLOFOIL RARE",
    color1: "white",
    color2: "black",
    color3: "black",
    color4: "black",
    color5: "black",
  },
  {
    rank: 5,
    name: "ULTRA RARE",
    color1: "white",
    color2: "black",
    color3: "black",
    color4: "black",
    color5: "black",
  },
  {
    rank: 6,
    name: "ULTIMATE RARE",
    color1: "white",
    color2: "black",
    color3: "black",
    color4: "black",
    color5: "black",
  },
  {
    rank: 7,
    name: "SECRET RARE",
    color1: "white",
    color2: "black",
    color3: "black",
    color4: "black",
    color5: "black",
  },
  {
    rank: 8,
    name: "ULTRA SECRET RARE",
    color1: "white",
    color2: "black",
    color3: "black",
    color4: "black",
    color5: "black",
  },
  {
    rank: 9,
    name: "SECRET ULTRA RARE",
    color1: "white",
    color2: "black",
    color3: "black",
    color4: "black",
    color5: "black",
  },
  {
    rank: 10,
    name: "PLATINUM SECRET RARE",
    color1: "white",
    color2: "black",
    color3: "black",
    color4: "black",
    color5: "black",
  },
  {
    rank: 11,
    name: "PRISMATIC SECRET RARE",
    color1: "white",
    color2: "black",
    color3: "black",
    color4: "black",
    color5: "black",
  },
  {
    rank: 12,
    name: "GHOST RARE",
    color1: "white",
    color2: "black",
    color3: "black",
    color4: "black",
    color5: "black",
  },
  {
    rank: 13,
    name: "PARALLEL RARE",
    color1: "white",
    color2: "black",
    color3: "black",
    color4: "black",
    color5: "black",
  },
  {
    rank: 14,
    name: "PARALLEL COMMON",
    color1: "white",
    color2: "black",
    color3: "black",
    color4: "black",
    color5: "black",
  },
  {
    rank: 15,
    name: "SUPER PARALLEL RARE",
    color1: "white",
    color2: "black",
    color3: "black",
    color4: "black",
    color5: "black",
  },
  {
    rank: 16,
    name: "ULTRA PARALLEL RARE",
    color1: "white",
    color2: "black",
    color3: "black",
    color4: "black",
    color5: "black",
  },
  {
    rank: 17,
    name: "DUEL TERMINAL EDITION",
    color1: "white",
    color2: "black",
    color3: "black",
    color4: "black",
    color5: "black",
  },
  {
    rank: 18,
    name: "DUEL TERMINAL PARALLEL COMMON",
    color1: "white",
    color2: "black",
    color3: "black",
    color4: "black",
    color5: "black",
  },
  {
    rank: 19,
    name: "DUEL TERMINAL NORMAL PARALLEL",
    color1: "white",
    color2: "black",
    color3: "black",
    color4: "black",
    color5: "black",
  },
  {
    rank: 20,
    name: "DUEL TERMINAL NORMAL PARALLEL RARE",
    color1: "white",
    color2: "black",
    color3: "black",
    color4: "black",
    color5: "black",
  },
  {
    rank: 21,
    name: "DUEL TERMINAL RARE PARALLEL RARE",
    color1: "white",
    color2: "black",
    color3: "black",
    color4: "black",
    color5: "black",
  },
  {
    rank: 22,
    name: "DUEL TERMINAL SUPER PARALLEL RARE",
    color1: "white",
    color2: "black",
    color3: "black",
    color4: "black",
    color5: "black",
  },
  {
    rank: 23,
    name: "DUEL TERMINAL ULTRA PARALLEL RARE",
    color1: "white",
    color2: "black",
    color3: "black",
    color4: "black",
    color5: "black",
  },
  {
    rank: 24,
    name: "DUEL TERMINAL SECRET PARALLEL RARE",
    color1: "white",
    color2: "black",
    color3: "black",
    color4: "black",
    color5: "black",
  },
  {
    rank: 25,
    name: "GOLD RARE",
    color1: "white",
    color2: "black",
    color3: "black",
    color4: "black",
    color5: "black",
  },
  {
    rank: 26,
    name: "GHOST SECRET RARE",
    color1: "white",
    color2: "black",
    color3: "black",
    color4: "black",
    color5: "black",
  },
  {
    rank: 27,
    name: "GHOST/GOLD RARE",
    color1: "white",
    color2: "black",
    color3: "black",
    color4: "black",
    color5: "black",
  },
  {
    rank: 28,
    name: "SHORT PRINT",
    color1: "white",
    color2: "black",
    color3: "black",
    color4: "black",
    color5: "black",
  },
  {
    rank: 29,
    name: "STARFOIL RARE",
    color1: "white",
    color2: "black",
    color3: "black",
    color4: "black",
    color5: "black",
  },
  {
    rank: 30,
    name: "MOSAIC RARE",
    color1: "white",
    color2: "black",
    color3: "black",
    color4: "black",
    color5: "black",
  },
  {
    rank: 31,
    name: "SHATTERFOIL RARE",
    color1: "white",
    color2: "black",
    color3: "black",
    color4: "black",
    color5: "black",
  },
  {
    rank: 32,
    name: "COLLECTOR'S RARE",
    color1: "white",
    color2: "black",
    color3: "black",
    color4: "black",
    color5: "black",
  },
  {
    rank: 33,
    name: "HOLOGRAPHIC PARALLEL RARE",
    color1: "white",
    color2: "black",
    color3: "black",
    color4: "black",
    color5: "black",
  },
  {
    rank: 34,
    name: "PLATINUM SECRET RARE",
    color1: "white",
    color2: "black",
    color3: "black",
    color4: "black",
    color5: "black",
  },
  {
    rank: 35,
    name: "PLATINUM RARE",
    color1: "white",
    color2: "black",
    color3: "black",
    color4: "black",
    color5: "black",
  },
];
